# Generated by Django 3.1 on 2020-08-22 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_billing_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='zip',
            new_name='zipcode',
        ),
    ]
