# Generated by Django 3.1 on 2020-08-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200825_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(default=20, max_length=100),
            preserve_default=False,
        ),
    ]
